name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure Docker registry
        uses: google/auth@v2
        with:
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

      - name: Login to Docker registry
        run: echo "$DOCKER_PASSWORD" | docker login -u _json_key --password-stdin https://gcr.io/$GOOGLE_CLOUD_PROJECT

      - name: Build and push image
        run: |
          docker build -t gcr.io/$GOOGLE_CLOUD_PROJECT/ac_app:latest .
          docker push gcr.io/$GOOGLE_CLOUD_PROJECT/ac_app:latest

      - name: Deploy to GKE
        uses: google/cloud-build/action@v1
        with:
          secret: ${{ secrets.github-actions-key }}
          substitutions: |
            _IMAGE=gcr.io/$GOOGLE_CLOUD_PROJECT/ac_app:latest

      - name: Rollback on failure (optional)
        uses: apps/app-deployer@v1.2.0
        with:
          deployment: ac-laboratory-deployment-v1
          kubeConfig: ${{ secrets.github-actions-key }}
          strategy: canary
        if: failure()

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}  # Optional if using Docker Hub
secrets:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.github-actions-key }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}  # Optional if not using secrets manager
