steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'val099/ac_app:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'val099/ac_app:$SHORT_SHA']
    secretEnv: ['DOCKERHUB_TOKEN']

  # Step 3: Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/cloud-app-deployment-v1', 'container-name=val099/ac_app:$SHORT_SHA']
    env: ['CLOUDSDK_COMPUTE_ZONE=europe-central2-a', 'CLOUDSDK_CONTAINER_CLUSTER=ac-laboratory-clusst3r']

# Secret required for pushing to Docker Hub
secrets:
  - kmsKeyName: projects/748761430178/locations/global/keyRings/key-ring/cryptoKeys/key
    secretEnv:
      DOCKERHUB_TOKEN: 'projects/748761430178/secrets/dockerhub-token'
