steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ac-m-laboratory/gke-repo/ac-cloud-app', '.']
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/ac-m-laboratory/gke-repo/ac-cloud-app:latest']
  id: 'Push Docker Image'

# Step 3: Deploy to GKE
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
    - '-xe'
    - '-c'
    - |
      gcloud deploy apply --file _deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file _deploy/prod.yaml --region=us-central1

      echo "SHORT_SHA: ${SHORT_SHA}" &&
      gcloud deploy releases create app-release-${SHORT_SHA}
      --delivery-pipeline=cicd--pipeline
      --region=us-central1
      --skaffold-file=skaffold.yaml

serviceAccount: 'projects/ac-m-laboratory/serviceAccounts/service@ac-m-laboratory.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
