steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/748761430178/gke-repo/ac-cloud-app', './' ]
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/748761430178/gke-repo/ac-cloud-app' ]
  id: 'Push Docker Image'

# Step 3: Deploy to GKE
- name: 'google/cloud-sdk:latest'
  args: ['-xe', '-c', '|', 
  'gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1', 
  'gcloud deploy apply --file deploy/dev.yaml --region=europe-central2-a', 
  'gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml']

options:
  logging: CLOUD_LOGGING_ONLY