---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - val099/ac_app:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - val099/ac_app:$SHORT_SHA
    secretEnv:
      - DOCKERHUB_TOKEN
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/cloud-app-deployment-v1
      - container-name=val099/ac_app:$SHORT_SHA
    env:
      - CLOUDSDK_COMPUTE_ZONE=your-zone
      - CLOUDSDK_CONTAINER_CLUSTER=your-cluster
secrets:
  - kmsKeyName: projects/ac-m-laboratory/locations/global/keyRings/key-ring/cryptoKeys/key
    secretEnv:
      DOCKERHUB_TOKEN: projects/ac-m-laboratory/secrets/dockerhub-token/versions/latest
