steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ac-m-laboratory/gke-repo/ac-cloud-app', '.']
  id: 'Build Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/ac-m-laboratory/gke-repo/ac-cloud-app:latest']
  id: 'Push Docker Image'

# Step 3: Deploy to GKE
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
    - '-xe'
    - '-c'
    - |
      gcloud config set deploy/region us-central1
      gcloud deploy apply --file _deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file _deploy/prod.yaml --region=us-central1

      RELEASE_NAME=projects/ac-m-laboratory/locations/us-central1/deliveryPipelines/cicd--pipeline/releases/app-release-${SHORT_SHA}

      echo "SHORT_SHA: ${SHORT_SHA}" &&
      gcloud deploy releases create ${RELEASE_NAME} \
      --delivery-pipeline=cicd--pipeline \
      --region=us-central1 \
      --from-k8s-manifest=_kube/deployment-v1.yaml

serviceAccount: 'projects/ac-m-laboratory/serviceAccounts/service@ac-m-laboratory.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
