apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment-v1
spec:
  replicas: 3 # Number of instances of the application
  selector:
    matchLabels:
      app: ac-laboratory-v1
  template:
    metadata:
      labels:
        app: ac-laboratory-v1
    spec:
      containers:
      - name: ac-laboratory-v1
        image: val099/ac_app:0.5
        ports:
        - containerPort: 80 # Expose the container on internal port 80 = EXPOSE in Dockerfile
  strategy: # update w\o downtime
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
