apiVersion: v1
kind: Service
metadata:
  name: ac-laboratory-service
spec:
  type: LoadBalancer
  ports:
  - port: 80 # Expose the service on internal port 80
    targetPort: 8080 # Send the traffic to container port 8080
  selector:
    app: ac-laboratory-v1
