
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app-deployment-v1
spec:
  replicas: 3 # Number of instances of the application
  selector:
    matchLabels:
      app: ac-lab-v1
  template:
    metadata:
      labels:
        app: ac-lab-v1
    spec:
      containers:
      - name: ac-lab-v1
        image: us-central1-docker.pkg.dev/ac-laboratory-423906/gke-repo/ac-cloud-app:latest
        ports: 
        - containerPort: 8080
  strategy: # update w\o downtime
    type: RollingUpdate
    rollingUpdate:
        maxUnavailable: 0
        maxSurge: 2

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: ac-laboratory-service
spec:
  type: LoadBalancer
  ports:
  - port: 80 # Expose the service on internal port 80
    targetPort: 8080 # Send the traffic to container port 8080
  selector:
    app: ac-lab-v1

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ac-laboratory-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloud-app-deployment-v1
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70