apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
gke:
  cluster: projects/ac-laboratory-423906/locations/us-central1-a/clusters/ac-laboratory-clusst3r